<?xml version="1.0" encoding="utf-8"?>
<LOG>
  <LOG ID="798602143" Data="02/08/2015 17:36:20">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>The provider did not return a ProviderManifestToken string. *** An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; workflow/edit</NameSpace>
    <Context />
    <StackTrace>   em System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.&lt;&gt;c__DisplayClass1.&lt;ResolveManifestToken&gt;b__0(Tuple`3 k)
   em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.ResolveManifestToken(DbConnection connection)
   em System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest&amp; providerManifest)
   em System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   em System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   em System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   em System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   em System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   em System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   em System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   em System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   em App_Dominio.Security.EmpresaSecurity`1._ValidarSessao(String sessionId)</StackTrace>
  </LOG>
  <LOG ID="912076459" Data="02/08/2015 17:36:53">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="DLAxN9sVgBSgGaNsyF8hLfeOux9H0cpRTyt3x3hZJoN43GPgGeqmXg93PWtksgsucsqhjDrG-QH1vxAalvY8EOmZxZ7vIRpStEW8kZm8i-o1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="560704568" Data="02/08/2015 17:36:53">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="DLAxN9sVgBSgGaNsyF8hLfeOux9H0cpRTyt3x3hZJoN43GPgGeqmXg93PWtksgsucsqhjDrG-QH1vxAalvY8EOmZxZ7vIRpStEW8kZm8i-o1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1557103487" Data="02/08/2015 17:37:27">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="DLAxN9sVgBSgGaNsyF8hLfeOux9H0cpRTyt3x3hZJoN43GPgGeqmXg93PWtksgsucsqhjDrG-QH1vxAalvY8EOmZxZ7vIRpStEW8kZm8i-o1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1557103487" Data="02/08/2015 17:37:27">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="DLAxN9sVgBSgGaNsyF8hLfeOux9H0cpRTyt3x3hZJoN43GPgGeqmXg93PWtksgsucsqhjDrG-QH1vxAalvY8EOmZxZ7vIRpStEW8kZm8i-o1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1763402197" Data="02/08/2015 17:38:52">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="5L6y_aNHh2pq3RXiu1p_XI7K6vxJO3ntQEiKZD208Ab6nXcmMJdLf1Co-uKRv7US-DzIl2hTJRXyNOyFGo7I8SX3LhKCb_e-hk7OHWuFJTE1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="386446478" Data="02/08/2015 17:38:52">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="5L6y_aNHh2pq3RXiu1p_XI7K6vxJO3ntQEiKZD208Ab6nXcmMJdLf1Co-uKRv7US-DzIl2hTJRXyNOyFGo7I8SX3LhKCb_e-hk7OHWuFJTE1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="618330761" Data="02/08/2015 17:38:52">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>The provider did not return a ProviderManifestToken string. *** An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; workflow/edit</NameSpace>
    <Context />
    <StackTrace>   em System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.&lt;&gt;c__DisplayClass1.&lt;ResolveManifestToken&gt;b__0(Tuple`3 k)
   em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.ResolveManifestToken(DbConnection connection)
   em System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest&amp; providerManifest)
   em System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   em System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   em System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   em System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   em System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   em System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   em System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   em System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   em App_Dominio.Security.EmpresaSecurity`1._ValidarSessao(String sessionId)</StackTrace>
  </LOG>
  <LOG ID="541339176" Data="02/08/2015 17:39:03">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="467v3cLq5rxKPviSo5GGxwNX_3TvEIsTJ5SzWzLWA4ZZWVF6SsbF9K3Cj_rzQ8eggj72WWgohHPyLS1VFrf1WhM3dxQvwvPz48tJ_zPN0Xs1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="541339176" Data="02/08/2015 17:39:03">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="467v3cLq5rxKPviSo5GGxwNX_3TvEIsTJ5SzWzLWA4ZZWVF6SsbF9K3Cj_rzQ8eggj72WWgohHPyLS1VFrf1WhM3dxQvwvPz48tJ_zPN0Xs1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1695904702" Data="02/08/2015 17:39:07">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="KPl7mqfdNzSq6cJ6As0zbaeokOzR0wksvbQcc4R_T-fhn9vTYDbX18BamJuB2uuJRDLHlvcanplDVEnbTRj4DMKsjWNhzWhJybexTGlx3ZA1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1695904702" Data="02/08/2015 17:39:07">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="KPl7mqfdNzSq6cJ6As0zbaeokOzR0wksvbQcc4R_T-fhn9vTYDbX18BamJuB2uuJRDLHlvcanplDVEnbTRj4DMKsjWNhzWhJybexTGlx3ZA1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="767703707" Data="02/08/2015 17:41:09">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>The provider did not return a ProviderManifestToken string. *** An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; workflow/edit</NameSpace>
    <Context />
    <StackTrace>   em System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.&lt;&gt;c__DisplayClass1.&lt;ResolveManifestToken&gt;b__0(Tuple`3 k)
   em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   em System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.ResolveManifestToken(DbConnection connection)
   em System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest&amp; providerManifest)
   em System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   em System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   em System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   em System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   em System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   em System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   em System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   em System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   em App_Dominio.Security.EmpresaSecurity`1._ValidarSessao(String sessionId)</StackTrace>
  </LOG>
  <LOG ID="68608836" Data="02/08/2015 17:41:48">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="wAwt61NGcZRXB8Ax7-AYJfXxDFBRHQz26nIDLQD_o0i56b8cfGUPqRFIzx5DTPnbL52CGNmIv7ygBtR5cs9wRyaCL1XbA-chAAom0ND-IxU1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="839136764" Data="02/08/2015 17:41:48">
    <Sessao>nxmycd1s1spw2myiimqkvphx</Sessao>
    <IP>::1</IP>
    <HostName>DANIEL-15R\Daniel</HostName>
    <Mensagem>An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="wAwt61NGcZRXB8Ax7-AYJfXxDFBRHQz26nIDLQD_o0i56b8cfGUPqRFIzx5DTPnbL52CGNmIv7ygBtR5cs9wRyaCL1XbA-chAAom0ND-IxU1",UserName="danielleal94@gmail.com",Password="everglades"</Context>
    <StackTrace />
  </LOG>
</LOG>